### ISSUE TITLE
Questionable name?

### ISSUE THREAD

**Issue by gecko0307** [raizam/gamedev_libraries#10]
First of all, I like the idea of such lists, they are very helpful - I discovered a couple of useful libraries for myself thanks to this project. It's definitely a great job, so thank you for it! 
I just wanted to question its name. I doubt that 'junkyard' is suitable. Most of the libraries listed here are well-known and respected projects, and calling them junk is somewhat offensive. I understand that this wasn't intented, but I would not be pleased if my project was included in a list called a 'junkyard'. Such name leaves an impression of abandoned low-value stuff, but it of course isn't so.
I think FLOSS community should be respectful and use non-offensive names. I can suggest calling such lists `awesome_<something>`, like `awesome_gfx` or `awesome_gamedev` (there're already 'awesome' lists for all major languages out there: [awesome-c](https://github.com/kozross/awesome-c), [awesome-python](https://github.com/vinta/awesome-python), etc.).

**Comment by nem0** [comment]
scrapyard?

**Comment by raizam** [comment]
Originally I wanted to call it *graveyard*, but I noticed some projects are still moving :trollface:

**Comment by gecko0307** [comment]
SDL2, Bullet, Assimp, bgfx, glm and many others are pretty much alive.

**Comment by skypjack** [comment]
`awesone_<something>` looks good. What about `awesome_junk` instead of `junkyard`? :trollface:

**Comment by r-lyeh** [comment]
I always thought "Awesome" word was too much elitist for many things that are not that awesome in those lists. Similarly, "junkyard" word is bad for many projects that are not junk in these lists.

I don't think that name really matters, but if so, what about something in between? 
humbleyard? kinda "it worked for me; i just hope it works for you too" spirit.
xD

**Comment by raizam** [comment]
I think this issue is relevant and should be debated further.
However, this page is not famous enough to make a name switch,
hence I'll make a decision when it reaches 500 stars :trollface:

**Comment by raizam** [comment]
after a long period of thinking, I made a decision to change the name of this repository, I hope this new name meets the expectations :)
