### ISSUE TITLE
Add "SFML" libary

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [raizam/gamedev_libraries#12]
Simple and Fast Media Library is a cross platform library that has a bunch of independent modules for system, input management (joysticks too), graphics over GL, audio over AL, and networking.

https://www.sfml-dev.org/

Follow that up with a screen management and transition effect library Swoosh:

https://github.com/TheMaverickProgrammer/Swoosh

**Comment by raizam** [comment]
I've just created the 'frameworks' section and added SFML.
Your project Swoosh looks nice but is specific to SFML, it doesn't really belong here

**Comment by TheMaverickProgrammer** [comment]
julianeisel/bWidgets is limited to Blender. Your point?

**Comment by raizam** [comment]
_bWidgets is a cross-platform widget toolkit, designed specifically for Blender, but **reusable as a standalone library**._
